# from bs4 import BeautifulSoup
# import requests
# page = requests.get('http://playlists.net/charts')
# soup = BeautifulSoup(page.content, 'html.parser')
# ss = soup.find_all('h4')
# xx = []
# for i in ss:
#     xx.append(i.string)

pl = [
    'Slowly Drifting',
    'Pop Unplugged',
    'morrissey',
    'queen',
    'ash - best of',
    'Hip Hop Road Trip',
    "Chic'",
    'Topsify USA Hip-Hop R&B Top 40',
    'Fresh Hits',
    'roy orbison',
    'beatles and others',
    'Pride',
    'prince',
    'boomtown rats',
    'Hip Hop - NEW SCHOOL',
    'Sad Indie | Folk | Singer-Songwriter',
    '1990 Top Tracks',
    'Rhyme Slayers ',
    'R&B Hits',
    'jukebox',
    'Topsify Greatest Hits',
    't.rex best of',
    "Best of 2010's",
    'Ultimate Country',
    'Hip Hop Cardio',
    'Artists To Watch',
    'indie dance',
    'Best Indie Tracks',
    'ultravox',
    'Indie Boutique 2017',
    'Queens of Pop and Rock',
    'phil collins / genesis',
    'Party Hits',
    'Acoustic Morning',
    'bryan adams',
    '20 Years Ago...Best Songs of 1997',
    'shakin stevens',
    'The Heist',
    'Vacation House',
    '100 Greatest Movie Soundtracks Ever',
    'the cure',
    'new order',
    'Baila Reggaeton!',
    'Songs to Sing in the Shower',
    'Behind Closed Doors',
    'punk tracks',
    'Topsify US New Music Friday',
    'Power Workout',
    'travis',
    'Future Chill',
    'stone roses',
    'SXSW',
    'Topsify - Top 50 Hits',
    'beautiful south / housemartins',
    'radiohead',
    'Ultimate Playbill',
    'Underground Indie: Lo-Fi, Noise Pop, Etc.',
    'cliff richard',
    'Mountain House',
    "80's tracks",
    'Upbeat + Summer Sun ',
    'Waves &amp; Swells',
    'adam ant',
    'Summer Party 2014',
    'Mood Booster',
    'Punk 101',
    'ramones',
    'joy division',
    'Driving alone at Night',
    'smiths',
    'oasis',
    'pet shop boys',
    'Halftime Hits',
    'Dance Mega Mix',
    'elvis presley',
    'FOLK CLASSICS GALORE',
    'The Pride of Belgium',
    'Happily Ever After',
    'EDM 2014 ',
    'Beach Bar Boutique-Vol10 (Extended Mix)',
    'Christian Hits',
    "'00s Hip Hop",
    'Topsify US Rock Top 40',
    '100 Best Songs of 2016',
    'elton john',
    'Deep Focus',
    'Hip Hop Monsters',
    'placebo',
    'Cardio',
    'Beach Vibes',
    'Indie 2017: Top Tracks',
    "Girls' Night ",
    'madness',
    'R.E.M',
    'Record Store Day',
    "90's Rock",
    'kings fire',
    "Best Of The 70's",
    'ocean colour scene',
    'michael jackson',
    'Daydreaming vol.1',
    'Fresh Dance Tracks',
    'george michael / wham',
    'TOP OF THE CHARTS PLAYLIST ',
    'Indie 2017: April Tracks',
    'All That Jazz',
    'The 90s Kid',
    'Ultimate Christmas Playlist',
    'alien sex fiend',
    'Pumping Iron',
    'green day',
    'coldplay',
    'Jam Bands',
    'Hip Hop - OLD SCHOOL',
    'Your Favorite Coffeehouse',
    'Blues Revolution',
    "Best Of The 60's",
    'Teen Party',
    'Decades of Rock - 90s',
    'Greatest songs ever',
    'billy joel',
    'pixies',
    ' Weekend Hangouts',
    'Daydreaming Away',
    'nirvana',
    'Topsify US Top 40',
    'Eclectic Classics',
    'u2 - best of',
    'Beach Bar Boutique: Vol9',
    'Beach Bar Boutique: Vol8',
    'VERANO 2014',
    'stereophonics',
    "Let's Dance Shall We?!",
    "Chillin' &amp; Grillin'",
    'Undiscovered Indie &amp; Folk Gems',
    '20 Years of Sphere of Hip-Hop',
    'Christmas Rocks',
    'weezer',
    'Topsify - Global Top 50',
    "I'm an 80's Baby",
    'The Syllabus',
    'glam- best of',
    "Rockin' Road Trip",
    'libertines',
    'Billboard Hot 100',
    'manics',
    "Hip Hop Don't Stop",
    "Totally 80's",
    "It's 5 O'clock Somewhere",
    'madonna',
    'Country Hits',
    'britpop',
    'kaiser chiefs',
    'cranes',
    'US Alternative Top 40',
    'For Those About To Rock',
    'new model army',
    'Indie Darlings',
    'Pop VIP',
    "Totally 90's",
    'Masters of Metal',
    'sex pistols and others',
    'Relive Harry Potter!',
    'david bowie',
    'take that / robbie williams',
    'GRAMMY NOMINEES (Past &amp; Present)',
    'duran duran',
    'howard jones',
    'Halloween Hits',
    "St. Paddy's Day",
    'Beach Party',
    'spiritualized and others',
    'muse best of',
    'Love Songs',
    'Love Hurts',
    'Decades of Rock - 80s',
    "90's Hip Hop",
    "TOP 999 of the 90's",
    "Today's Top Hits",
    'sham 69',
    'adam and the ants',
    'All Hail the Guitar Gods',
    "Best Of the 2000's",
    'buddy holly',
    'CrossFit Pop',
    'Timeless Love Songs',
    'neds - best of'
]

import datetime
from core.db import cursor

for i in pl:
    now = datetime.datetime.now()
    cursor.keywords.update_one(
        {'word': i},
        {
            '$set': {
               'word': i,
               'created_date': now,
               'turn_date': now - datetime.timedelta(days=16),
               'loops': 1,
               'loop': 0,
               'total': 1
            }
        },
        upsert=True
    )
